sudo: false
language: node_js
cache:
  directories:
    - "node_modules"

node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g jest
  - npm install

script:
  - npm run test
