language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
notifications:
  email: false
before_script:
  - npm install
  - npm install jest-cli --save
  - npm install react-scripts --save
script:
  - npm test -- -u
